name: SimpleCI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: 4dcfe500a9a842ec5c817ed43f8f51b8b142716974e24d571e2c946a09563f18
        with:
          coverageCommand: make test-coverage
          debug: true
